### Flask Server Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-flask-sa-k8s
spec:
  selector:
    matchLabels:
      name: server-flask-sa-k8s
  template:
    metadata:
      labels:
        name: server-flask-sa-k8s
    spec:
      containers:
      - name: server-flask-sa-k8s
        image: app-sa:latest
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 6000
        env:
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: deployment.environment=app-smartagent
        - name: OTEL_SERVICE_NAME
          value: server-flask-sa-k8s
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: http://$(SPLUNK_OTEL_AGENT):9080/v1/trace
        - name: OTEL_TRACES_EXPORTER
          value: jaeger-thrift-splunk
        command: ["/bin/sh"]
        args: ["run-server-sa.sh"]
---
### Flask Server Service
apiVersion: v1
kind: Service
metadata:
  name: server-flask-sa-k8s
spec:
  selector:
    name: server-flask-sa-k8s
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 6000
---
### Python Requests Pod
apiVersion: v1
kind: Pod
metadata:
  name: client-py-sa-k8s
spec:
  containers:
  - name: client-py-sa-k8s
    image: app-sa:latest
    imagePullPolicy: Never
    env:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: deployment.environment=app-smartagent
    - name: OTEL_SERVICE_NAME
      value: client-py-sa-k8s
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_EXPORTER_JAEGER_ENDPOINT
      value: http://$(SPLUNK_OTEL_AGENT):9080/v1/trace
    - name: OTEL_TRACES_EXPORTER
      value: jaeger-thrift-splunk
    command: ["/bin/sh"]
    args: ["run-client-sa.sh"]